name: Greeting

on:
  issues:
    types:
      - opened
  pull_request:
    types:
      - opened

jobs:
  greet-user:
    runs-on: ubuntu-latest
    steps:
      - name: Check if it's the user's first issue or PR
        id: check-first-issue-pr
        run: |
          USER_LOGIN=${{ github.event.issue.user.login }}
          USER_ISSUES_COUNT=$(curl -s "https://api.github.com/search/issues?q=is:issue+is:open+author:${USER_LOGIN}" | jq -r .total_count)
          USER_PRS_COUNT=$(curl -s "https://api.github.com/search/issues?q=is:pr+is:open+author:${USER_LOGIN}" | jq -r .total_count)
          
          echo "Hello @${{ github.actor }}!"
          echo "Congratulations on opening your first issue in the PythonScriptsHub repository! 🎉 Your contribution is valuable to us! 😊"
          echo ""
          echo "Please make sure to follow our [Contributing Guidelines. 💪🏻](https://github.com/Swapnil-Singh-99/PythonScriptsHub/blob/main/CONTRIBUTING.md)"
          echo ""
          echo "Our review team will carefully assess the issue and reach out to you soon!"
          echo "We appreciate your patience!"
        
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Greet user if it's their first issue or PR
        if: steps.check-first-issue-pr.outputs.IS_FIRST_ISSUE == 'true' || steps.check-first-issue-pr.outputs.IS_FIRST_PR == 'true'
        run: |
          echo "Thank you, @${{ github.actor }}, on submitting your very first pull request to the PythonScriptsHub repository! 🥳"
          echo ""
          echo "The maintainers will review this Pull Request and provide feedback as soon as possible!"
          echo "We appreciate your patience and contribution, Keep up the great work! 😀"
